-- AlterTable
ALTER TABLE `project_task_types` MODIFY `type` ENUM('DEVELOPMENT', 'BUSINESS', 'OPERATION', 'SALES', 'QA', 'IT', 'OTHER', 'COMPANY', 'LEAVE', 'HR', 'ACCOUNTING', 'GRAPHIC_DESIGN', 'MEDIA') NOT NULL;

-- AlterTable
ALTER TABLE `task_types` MODIFY `type` ENUM('DEVELOPMENT', 'BUSINESS', 'OPERATION', 'SALES', 'QA', 'IT', 'OTHER', 'COMPANY', 'LEAVE', 'HR', 'ACCOUNTING', 'GRAPHIC_DESIGN', 'MEDIA') NOT NULL;
